### ISSUE TITLE
yum.Errors.MiscError: Invalid version flag: if

### ISSUE THREAD

**Issue by asterbini** [rpm-software-management/yum#102]
I have just upgraded Fedora from version 28 to 30 through `dnf system-upgrade`.
When I try to use `package-cleanup --problems` I get the error

> yum.Errors.MiscError: Invalid version flag: if

This seems to be due to the function `misc.string_to_prco_tuple` that is not able to parse the string `if (mysql-selinux if selinux-policy-targeted)`

**Comment by j-mracek** [comment]
I would recommend to use `dnf check` command. I believe that the functionality is similar.

Also I want to point out that yum/yum-utils based on yum will be not present in Fedora 31. There is a compatibility package (`dnf-utils`) that provides compatibility with yum-utils using functionality from `dnf` and `dnf-plugins`.

**Comment by dmnks** [comment]
Thank you for the report. However, please note that this project has been deprecated and is no longer maintained upstream. Please consider migrating to [DNF](https://github.com/rpm-software-management/dnf) which is the successor of YUM. That said, I’ll close this issue now.
