### ISSUE TITLE
get list of available updates without yum lock

### ISSUE THREAD

**Issue by survient** [rpm-software-management/yum#105]
I'm looking for a method to print a list of available updates without locking the yum database. I notice that after an initial yum check-update any subsequent check-update commands executed shortly thereafter resolve much more quickly. Is this data cached and if so is there a way to pull from that cache without locking the yum database?

**Comment by dmnks** [comment]
Thank you for the report. However, please note that this project has been deprecated and is no longer maintained upstream. Please consider migrating to [DNF](https://github.com/rpm-software-management/dnf) which is the successor of YUM. That said, I’ll close this issue now.
