### ISSUE TITLE
yum list output formatting broken

### ISSUE THREAD

**Issue by ziptie** [rpm-software-management/yum#116]
The output of, for example, 'yum list installed' is arguably almost never examined without first piping it through something like grep or less.  For some reason piped output is formatted to fixed width columns, so the third column begins at position 58 on the line, and adds newlines to align to column boundaries.  There should be, at the very least, some knob to let one turn that behaviour off. akin to --color.  See, for example, `ls -1`.

Here is a reference to others suffering this:
https://unix.stackexchange.com/questions/274938/how-to-get-yum-list-output-to-stay-on-one-line-when-getting-output-via-remote

My yum version is from rhel 7.4; --version reports: 3.4.3

Thanks!

**Comment by dmnks** [comment]
Thank you for the report. However, please note that this project has been deprecated and is no longer maintained upstream. Please consider migrating to [DNF](https://github.com/rpm-software-management/dnf) which is the successor of YUM. That said, I’ll close this issue now.
