### ISSUE TITLE
Need to change source code of YUM , so that instead of YUM installing the RPM, I will trigger the rpm -ivh command myself 

### ISSUE THREAD

**Issue by thejdeep** [rpm-software-management/yum#2]
Which part of the source code should I change ?

**Comment by Conan-Kudo** [comment]
Just use `yumdownloader --resolve` to have it do everything except installing the package. The tool is part of `yum-utils` package. Just install that, and use `yumdownloader` to download the packages you want to manually install.

Though, this sort of defeats the point of Yum...

**Comment by james-antill** [comment]
Note that -i is for installs, and won't work for upgrades.

But the bit you want to change is runTransaction() / processTransaction() ... or create a plugin and hook into pretransaction.
