### ISSUE TITLE
how to download yum rpm to intel's machine and install in another ARM64 machine

### ISSUE THREAD

**Issue by JohnGW05** [rpm-software-management/yum#36]
hi,
Could I download yum rpm to intel's machine and install in another ARM64 machine？ because I have a x86 machine which can surfer internet and a arm64 machine which cannot surfer internet, but I need use yum to install massive RPM to ARM64. wish your response, thank you very much
                                                                                                                              Best Regards

**Comment by dmnks** [comment]
First, you have to find a mirror with aarch64 packages.  For CentOS, you can go here and choose one:
https://www.centos.org/download/altarch-mirrors/
(I chose http://mirrors.dotsrc.org/centos-altarch/7.4.1708/os/aarch64/ for the example below)

Then, you have to create a new repo config for this mirror, for example:
```
# cat /etc/yum.repos.d/arm.repo
[arm]
name=arm
baseurl=http://mirrors.dotsrc.org/centos-altarch/7.4.1708/os/aarch64/
```

Next, import the public key:
`rpm --import http://mirrors.dotsrc.org/centos-altarch/7.4.1708/os/aarch64/RPM-GPG-KEY-CentOS-7-aarch64`

Finally, run:
`yumdownloader --archlist=aarch64 --disablerepo=\* --enablerepo=arm <pkg1> <pkg2> ...`
This will download the aarch64 packages into the current directory, which you can then transfer to your ARM64 machine and install there.
