### ISSUE TITLE
Yum history always shows user as System <unset> in AIX

### ISSUE THREAD

**Issue by ayappanec** [rpm-software-management/yum#42]
# yum history
ID     | Command line             | Date and time    | Action(s)      | Altered
-------------------------------------------------------------------------------
   272 | erase -y bison           | 2017-06-09 03:24 | Erase          |    1 EE
   271 | install -y bison         | 2017-06-09 03:24 | Install        |    1 EE
   270 | erase -y git             | 2017-06-09 02:22 | Erase          |    1
   269 | install -y git           | 2017-06-09 02:22 | Install        |    1
   268 | erase -y git             | 2017-06-08 21:55 | Erase          |    1
   267 | install make             | 2017-06-07 09:54 | Install        |    1 EE
   266 | install subversion       | 2017-06-07 09:49 | Install        |    1
   265 | install httpd            | 2017-06-07 09:48 | Install        |    2 EE
   264 | install tla              | 2017-06-07 09:44 | Install        |    3 EE
   263 | install bash curl expat  | 2017-06-07 09:44 | Update         |    2 EE
   262 | install coreutils curl-d | 2017-06-07 09:43 | Install        |    1
   261 | erase grep-3.0-1.ppc     | 2017-06-07 06:41 | Erase          |    1
   260 | erase -y pcre            | 2017-06-07 03:00 | Erase          |    1
   259 | install -y pcre          | 2017-06-07 03:00 | Install        |    1
   258 | install grep             | 2017-06-07 02:09 | Install        |    1
   257 | erase -y pcre            | 2017-06-07 01:38 | Erase          |    3 EE
   256 | erase -y vim             | 2017-06-07 01:10 | Erase          |    1
   255 | install -y vim           | 2017-06-07 01:09 | I, U           |    2
   254 | erase -y vim             | 2017-06-07 00:37 | Erase          |    1
   253 | install -y vim           | 2017-06-07 00:37 | Install        |    1
history list

(0) root @ aixoss-automation-2: 6.1.0.0: /opt/freeware/etc/yum/repos.d
# yum history info 263
Transaction ID : 263
Begin time     : Wed Jun  7 09:44:04 2017
Begin rpmdb    : 107:4862ad7227bc760f3d3f5f0c4cf3c4410c7ff593
End time       :            09:44:15 2017 (11 seconds)
End rpmdb      : 107:a3665a21e5b27567f29a034aa57fe2870fed5222
User           : System <unset>
Return-Code    : Success
Command Line   : install bash curl expat gettext less perl python rsync zlib
Transaction performed with:
    Installed     yum-3.4.3-4.noarch installed
Packages Altered:
    Updated bash-4.3.30-1.ppc @?AIX_Toolbox_local
    Update       4.4-1.ppc    @AIX_Toolbox_local
    Updated less-481-1.ppc    @?AIX_Toolbox_local
    Update       487-1.ppc    @AIX_Toolbox_local

**Comment by ayappanec** [comment]
The user is always reported as System<unset> in AIX machines. Any idea what is the logic behind that ?

**Comment by james-antill** [comment]
That's not a big surprise as it uses the Linux kernel loginuid mechanism:

https://github.com/rpm-software-management/yum/blob/master/yum/misc.py#L971

**Comment by ayappanec** [comment]
@james-antill Thanks for the info. In AIX, there is no such file like "/proc/self/loginuid" which stores the loginuid. But there is this command "id -l -u" which retrieves the loginuid. Does it make sense if we use this in the python script for AIX OS ? Is a patch welcome here ?

**Comment by james-antill** [comment]
No, what you want is to somehow call the AIX API: getuidx(ID_LOGIN)

https://www.ibm.com/support/knowledgecenter/en/ssw_aix_61/com.ibm.aix.basetrf1/getuid.htm

**Comment by ayappanec** [comment]
Okay but Python has ctypes library loading issue in AIX where libc is in archive format (libc.a). 

>>> from ctypes import *
>>> cdll.LoadLibrary("libc.a")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/freeware/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "/opt/freeware/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError:        0509-022 Cannot load module /usr/lib/threads/libc.a.
        0509-103   The module has an invalid magic number.

So calling the AIX API getuidx(ID_LOGIN) from python doesn't work it seems.

**Comment by ayappanec** [comment]
Due to the above mentioned problem, i tried invoking the aix id command (/usr/bin/id -l -u ) to get the loginuid. One can see the changes here --> https://github.com/aixoss/yum/commit/4122be9b5ffa68571ed18e2333f67689d017dc42
I test this patch in AIX and it works.

**Comment by ayappanec** [comment]
Python ctypes library loading issue in AIX https://bugs.python.org/issue27435
Till this issue is resolved , i think we need to go with the above approach. Can i go for a PR ?

**Comment by james-antill** [comment]
Sure, just add a comment about the API pointing to the above.
