### ISSUE TITLE
from_repo validators broke file install output

### ISSUE THREAD

**Issue by james-antill** [rpm-software-management/yum#49]
Local/http install rpms get a repo of "/rn-v-r.a", which doesn't validate via. misc.validate_repoid
This means they don't get output in Eg. yum list foo, and even make yumdb traceback. This hack fixes it:

```
% syum fs diff /usr/lib/python2.7/site-packages/yum
diff -ru /tmp/tmp6ZWVHx/usr/lib/python2.7/site-packages/yum/rpmsack.py /usr/lib/python2.7/site-packages/yum/rpmsack.py
--- /tmp/tmp6ZWVHx/usr/lib/python2.7/site-packages/yum/rpmsack.py	2017-08-31 15:56:13.712179010 -0400
+++ /usr/lib/python2.7/site-packages/yum/rpmsack.py	2017-08-31 15:55:08.638097415 -0400
@@ -1731,6 +1731,11 @@
 
         pass
 
+def _hack_valid_repoid(repoid):
+    if repoid and repoid[0] == '/':
+        return misc.validate_repoid(repoid[1:])
+    return misc.validate_repoid(repoid)
+
 class RPMDBAdditionalDataPackage(object):
 
     # We do auto hardlink on these attributes
@@ -1744,7 +1749,7 @@
     # Validate these attributes when they are read from a file
     _validators = {
         # Fixes BZ 1234967
-        'from_repo': lambda repoid: misc.validate_repoid(repoid) is None,
+        'from_repo': lambda repoid: _hack_valid_repoid(repoid) is None,
     }
 
     def __init__(self, conf, pkgdir, yumdb_cache=None):
diff -ru /tmp/tmp6ZWVHx/usr/lib/python2.7/site-packages/yum/rpmsack.pyc /usr/lib/python2.7/site-packages/yum/rpmsack.pyc
Binary files /tmp/tmp6ZWVHx/usr/lib/python2.7/site-packages/yum/rpmsack.pyc and /usr/lib/python2.7/site-packages/yum/rpmsack.pyc differ

```

**Comment by dmnks** [comment]
Hello James,

`_ui_from_repo()` actually returns `installed` for such packages, which is then also output as their origin in `yum list`.

Is there any way to reproduce the issue you're seeing? I have tried simply installing a local package with `yum install` so far, which works (it prints `installed` as I mentioned).

Thanks!

**Comment by james-antill** [comment]
If you use "yumdb info" it'll traceback ... and "installed" is also an error, it should print the filename. You can look at what is in the file directly to see what is there.

**Comment by dmnks** [comment]
Ok, I tried this without the from_repo validator in place (the way it was before the patch), and it really printed the filename for me as well. And yumdb info indeed crashes with the validator.

I'll see if we can fix it somehow without the hack you proposed, but we might as well just use that :)

Thanks
