### ISSUE TITLE
Typo on the word "lanuages"

### ISSUE THREAD

**Issue by mforsetti** [rpm-software-management/yum#64]
A typo for the word "languages" (I assume) on https://github.com/rpm-software-management/yum/blob/1bc3d51235cfbb060ea9f1b5ab1fc4804653ce61/yumcommands.py#L4385

**Comment by dmnks** [comment]
Thank you for the report. However, please note that this project has been deprecated and is no longer maintained upstream. Please consider migrating to [DNF](https://github.com/rpm-software-management/dnf) which is the successor of YUM. That said, I’ll close this issue now.
