### ISSUE TITLE
A yum command to show just the version of package installed

### ISSUE THREAD

**Issue by tapaswenipathak** [rpm-software-management/yum#70]
[Here](https://access.redhat.com/sites/default/files/attachments/rh_yum_cheatsheet_1214_jcs_print-1.pdf) is yum commands cheatsheet.

`yum info package-name` shows info something like

```
Name           : package-name
Arch           : arch_type
Version        : version_number
Release        : release_number
Size           :  size
Repo           : repo-name
Summary        : some_summary
License        : license_name
Description    : description
```

I understand that all this is important information to show on how yum packaging works. I always had a thought if there have been some work/discussion around having a command which would just output the version and not all other info? 

Please close the ticket if this is noise for yum issue queue, I'll go to SO or Quora or yum mailing list to see if can get some information around this, just curious. or if there is something i'm gonna learn new.

**Comment by james-antill** [comment]
"yum list" just shows the version. There's also repoquery --qf, if you want specific information (Eg. --qf '%{ui_nevra} %{summary}'

**Comment by tapaswenipathak** [comment]
`yum list package-name` would show something like

```
Installed Packages
package-name              version_number                      installed
Available Packages
package-name              version_number                      repo-name

```

I was looking for something how non yum say `docker --version` would output.

`yum list installed package-name` gives something like

```
Installed Packages
package-name.arch-type                version-number            installed/repo_name
```

Thanks for sharing about `repoquery`, I tried to run it has `repoquery --qf '%{package-name} %{summary/Version}'` it didn't seem to work. When I tried with `repoquery --qf *package-name` I was able to get the info how `rpm -q package-name` would give, something like `package-name:version-number.arch_type` for a specific package.

Can you share if I'm missing something in syntax of using repoquery just to extract the version? feel free to throw a link or a read if this is very basic question, I have just tried a few things with the syntax.

**Comment by james-antill** [comment]
I'm still not sure exactly what you want, there is some help in the man page (man repoquery) and also repoquery --querytags.

Taking a guess though:

    repoquery --qf '%{name}.%{arch} %{version} %{ui_from_repo}'
