### ISSUE TITLE
"yum clean all" does not remove urlgrabber's download host timing file

### ISSUE THREAD

**Issue by elyscape** [rpm-software-management/yum#71]
This is a crosspost of [RHBZ #1465172][bugzilla].

#### Description of problem
Yum, through the urlgrabber Python module, keeps track of which hosts are the quickest to download files from. This is generally useful, but can cause problems in some situations if it gets out of date (e.g. when cached in a Docker image).  Unfortunately, while `yum clean all` cleans up most cached data, it does not remove the urlgrabber download host timing file.

#### Version-Release number of selected component (if applicable)
yum: 3.4.3-150.el7.centos
python-urlgrabber: 3.10-8.el7

#### How reproducible
Trivial.

#### Steps to Reproduce
As root (or with sudo in front of each command):
```shell
find /var/cache/yum -mindepth 1 -delete # clean up the cache
find /var/cache/yum -name timedhosts
yum -q makecache fast
find /var/cache/yum -name timedhosts
yum clean all
find /var/cache/yum -name timedhosts
```

#### Actual results
```shellsession
# find /var/cache/yum -mindepth 1 -delete # clean up the cache
# find /var/cache/yum -name timedhosts
# yum -q makecache fast
# find /var/cache/yum -name timedhosts
/var/cache/yum/x86_64/7/timedhosts
# yum clean all
Loaded plugins: fastestmirror, ovl
Cleaning repos: base extras updates
Cleaning up everything
Cleaning up list of fastest mirrors
# find /var/cache/yum -name timedhosts
/var/cache/yum/x86_64/7/timedhosts
# 
```

#### Expected results
```shellsession
# find /var/cache/yum -name timedhosts
# 
```

#### Additional info
This is not caused by the fastestmirror plugin, which by default uses a file named `timedhosts.txt`. It is caused by [the timedhosts functionality of urlgrabber][timedhosts]. This feature is disabled by default but was enabled in the Yum core in 9fdc18d828565ebddf5ccd993b93fffd4be519a7, which has the following commit message:

>enable timedhosts
>
>Q: Make it configurable?

This was never followed up on. While it would be nice if it were possible to configure the use of timedhosts or the path to the file it uses, the primary issue is the fact that the timedhosts file is not removed during cleanup. It probably makes the most sense to handle this in the `yum clean metadata` command, which is [implemented in cleanMetadata][cleanMetadata].

[bugzilla]: https://bugzilla.redhat.com/show_bug.cgi?id=1465172
[timedhosts]: https://github.com/rpm-software-management/urlgrabber/blob/master/urlgrabber/grabber.py#L303-L308
[cleanMetadata]: https://github.com/rpm-software-management/yum/blob/1bc3d51235cfbb060ea9f1b5ab1fc4804653ce61/yum/__init__.py#L2867-L2873

**Comment by dmnks** [comment]
Thank you for the report. However, please note that this project has been deprecated and is no longer maintained upstream. Please consider migrating to [DNF](https://github.com/rpm-software-management/dnf) which is the successor of YUM. That said, I’ll close this issue now.
