### ISSUE TITLE
yum-cron ignores "update_messages = no" after downloading updates

### ISSUE THREAD

**Issue by andymwood** [rpm-software-management/yum#72]
I have configured yum-cron to download updates on some machines, but not apply them. Every time it does this it sends an email. I do not wish to receive such emails and have set "update_messages = no" in /etc/yum/yum-cron.conf, but yum-cron appears to be ignoring this option.

Is this intended behaviour?

The comment in /etc/yum/yum-cron.conf says "Whether a message should be emitted when updates are available, were downloaded, or applied."

**Comment by pagaille** [comment]
I'm also annoyed by this setting that looks to be broken. Any update on this ?

**Comment by dmnks** [comment]
Thank you for the report. However, please note that this project has been deprecated and is no longer maintained upstream. Please consider migrating to [DNF](https://github.com/rpm-software-management/dnf) which is the successor of YUM. That said, I’ll close this issue now.
