### ISSUE TITLE
Calling import_key_to_pubring without cachedir or gpgdir leads to interesting results

### ISSUE THREAD

**Issue by antevens** [rpm-software-management/yum#8]
The bug isn't very noticeable since mostly things will work, it creates the gpgdir in the wrong place and even if you change your current dir it will just create another bogus directory.

The other issue is that is sets the environment variable permanently and when another app then tries to start GPG it will fail horribly since None/gpgdir does not work well as a default GPG dir.

```
def import_key_to_pubring(rawkey, keyid, cachedir=None, gpgdir=None, make_ro_copy=True):
    # FIXME - cachedir can be removed from this method when we break api
    if gpgme is None:
        return False

    if not gpgdir:
        gpgdir = '%s/gpgdir' % cachedir     <- Now gpgdir ==  None/gpgdir

    if not os.path.exists(gpgdir):
        os.makedirs(gpgdir)                       <- And apparently we create that directory

    key_fo = StringIO(rawkey) 
    os.environ['GNUPGHOME'] = gpgdir      <- And then set env var with wrong value without ever unsetting
    # import the key
    ctx = gpgme.Context()
    fp = open(os.path.join(gpgdir, 'gpg.conf'), 'wb')
    fp.write('')
    fp.close()
    ctx.import_(key_fo)
    key_fo.close()
    # ultimately trust the key or pygpgme is definitionally stupid
    k = ctx.get_key(keyid)
    gpgme.editutil.edit_trust(ctx, k, gpgme.VALIDITY_ULTIMATE)

    if make_ro_copy:

        rodir = gpgdir + '-ro'
        if not os.path.exists(rodir):
            os.makedirs(rodir, mode=0755)
            for f in glob.glob(gpgdir + '/*'):
                basename = os.path.basename(f)
                ro_f = rodir + '/' + basename
                shutil.copy(f, ro_f)
                os.chmod(ro_f, 0755)
            fp = open(rodir + '/gpg.conf', 'w', 0755)
            # yes it is this stupid, why do you ask?
            opts="""lock-never    
no-auto-check-trustdb    
trust-model direct
no-expensive-trust-checks
no-permission-warning         
preserve-permissions
"""
            fp.write(opts)
            fp.close()


    return True
```

**Comment by dmnks** [comment]
What's your use case for having both `cachedir` and `gpgdir` set to `None`?  In yum, we always supply `gpgdir` (from `repo.gpgdir`) when calling `import_key_to_pubring` and it is never `None` (`cachedir`, on the other hand, is always `None`), so this shouldn't be a problem there.

The reason I'm asking is that I'm not sure what the behavior should be if both are `None`. Would returning `False` be sufficient? (Other than that, I do agree that not handling this case is a bug.)

**Comment by dmnks** [comment]
This project has been deprecated and is no longer maintained upstream. Please consider migrating to [DNF](https://github.com/rpm-software-management/dnf) which is the successor of YUM. That said, I’ll close this issue now.
