### ISSUE TITLE
yum autoremove tries to remove systemd

### ISSUE THREAD

**Issue by jamescassell** [rpm-software-management/yum#80]
When running `yum autoremove`, yum tries to remove systemd, even though systemd is marked as 'reason: user' in yumdb.

In my case, I'm trying to remove policycoreutils-python (in a container), which indirectly depends on shadow-utils, which is required by systemd.

I can workaround the issue by `yumdb set reason user shadow-utils` to make the autoremove successful.

The reason seems to be that required_packages() and requiring_packages() do not run recursively:
https://github.com/rpm-software-management/yum/blob/1222f377b8dcecb77456ea378a28e1dc23ba4207/yum/rpmsack.py#L115-L128
https://github.com/rpm-software-management/yum/blob/1222f377b8dcecb77456ea378a28e1dc23ba4207/yum/rpmsack.py#L131-L138

**Comment by dmnks** [comment]
Thank you for the report. However, please note that this project has been deprecated and is no longer maintained upstream. Please consider migrating to [DNF](https://github.com/rpm-software-management/dnf) which is the successor of YUM. That said, I’ll close this issue now.
