### ISSUE TITLE
 yum command argument is not optional 

### ISSUE THREAD

**Issue by swadeley** [rpm-software-management/yum#87]
Hello, this text:

SYNOPSIS
       yum [options] [command] [package ...]

Should be:

SYNOPSIS
       yum [options] COMMAND [package ...]

**Comment by dmnks** [comment]
This was [fixed](https://github.com/rpm-software-management/yum/commit/7522529957a8b769d91bd7f6762e31d7b9ee29fa) (and [fixed up](https://github.com/rpm-software-management/yum/pull/104)) some time ago, closing the issue now.
