### ISSUE TITLE
Support on python3

### ISSUE THREAD

**Issue by RyanSiu1995** [rpm-software-management/yum#91]
Hi,
python2 is going to be deprecated in the upcoming year.
I have widely used the yum sdk for my own development.
I would like to ask for the publish on python3 for this yum sdk.
Thank you!

**Comment by j-mracek** [comment]
Thank a lot for using an rpm software. There is an rpm manager available for Python3 called DNF. I would recommend to port your code or workflows to use DNF. DNF could be build for Python2 and also Python3, therefore there is an additional flexibility. DNF also provides very good command-line compatibility with yum.

**Comment by RyanSiu1995** [comment]
Awesome! Let me take a look at DNF first. Thank you!

**Comment by anatol** [comment]
There are a lot of scripts where `yum` is still used and it would require some time to refactor it for `dnf`. It would still be great to make the tool python2/3 compatible.

**Comment by lukash** [comment]
@anatol FWIW, dnf should be pretty much compatible with yum. yum is not going to be ported to Python 3, so I'd say the sooner you refactor your tools, the better for you...
