### ISSUE TITLE
Output response body or log file location when receiving a 503 response code

### ISSUE THREAD

**Issue by ElijahLynn** [rpm-software-management/yum#92]
Just spend a couple hours debugging an issue inside a firewall where `yum` was getting a 503 response code but no response body. And a message around "Failure talking to yum: Cannot find a valid baseurl for repo: remi". Turns out it was blocked by the firewall and `tshark` actually showed the whole response body, explaining the reason for the 503 (blocked `yum` useragent) and who to email etc. 

`yum` needs to output the response body or a log file location with the response body in it. A user shouldn't need `tshark` to read the response body of a 503. 

How does this sound or is their a functionality built into `yum` already to show this information? eg. debug mode etc. 

Even if there is most users won't know about it and if there is a 503 then yum should probably at least say "re-run yum with --debug to see all response bodies".

**Comment by ElijahLynn** [comment]
Also, side-issue "Failure talking to yum: Cannot find a valid baseurl for repo: remi" could be better phrased.

"Failure talking to yum" => How is this possible, it is yum. Yum can't have a failure talking to itself. How can we better word this?

"Cannot find a valid baseurl for repo: remi" => To me this implied it couldn't find a baseurl in the /etc/yum.repos.d/remi.repo config, and when I open it, there is a commented out baseurl. But in reality it was trying to "contact" another, default baseurl, that wasn't in that file. So maybe "Cannot establish connection to baseurl $BASEURL for repo: remi" would be better.

**Comment by dmnks** [comment]
Thank you for the report. However, please note that this project has been deprecated and is no longer maintained upstream. Please consider migrating to [DNF](https://github.com/rpm-software-management/dnf) which is the successor of YUM. That said, I’ll close this issue now.
